### ISSUE TITLE
API Gateway as a service-to-service communication

### ISSUE THREAD

**Issue by jodafm** [aws-samples/aws-serverless-ecommerce-platform#106]
Hey guys, I just want your opinion about use API Gateway as a service-to-service
communication
Is this really a bad pattern?
API-GATEWAY -> LAMBDA -> API-GATEWAY -> LAMBDA

**Comment by nmoutschen** [comment]
Hey! Thanks for reaching out!

From my point of view, it's not a bad pattern at all. From a pure micro-service architecture perspective, it creates well-decoupled interfaces. That gives you the flexibility to make changes on what's happening behind the API gateway as long as you maintain the API contract: splitting a function that's handling multiple paths/methods into smaller ones, merging functions, replacing a Lambda function with something else (e.g. direct integration with DynamoDB), etc.

However, in term of tradeoffs, having multiple components in the calling chain will increase costs and overall latency. So there is a limit on the depth (how many services will you chain) before it will negatively impact the end-users.

That's why the [frontend-api](https://github.com/aws-samples/aws-serverless-ecommerce-platform/tree/master/frontend-api) service tends to access DynamoDB tables directly: as this is a customer-facing API, latency should be low. It's breaking the boundaries between the frontend API and micro-services, but at the benefit of latency and costs. However, if you look at the CreateOrder path, it goes like this: `AppSync -> Lambda -> Multiple API Gateways -> Multiple Lambda functions`.

While talking about latency, that's why moving things to asynchronous workflow early is nice. For example, when [creating an order](https://github.com/aws-samples/aws-serverless-ecommerce-platform/tree/master/orders), the user will get a response when the data is persisted in DynamoDB. However, this is not the end of the flow: a Lambda function is then invoked from the data in DynamoDB streams to emit an event on EventBridge, which is picked up by a Lambda function in the [warehouse service](https://github.com/aws-samples/aws-serverless-ecommerce-platform/tree/master/warehouse).

The flow is like this: `AppSync -> Lambda -> DynamoDB -> Lambda -> EventBridge -> Lambda -> DynamoDB`. The part that is latency sensitive is only `AppSync -> Lambda -> DynamoDB`. On top of the latency part, this also minimizes the blast radius of errors. E.g. if there's a failure to process the event from the warehouse service, the order can still be created and the warehouse service has a dead-letter queue to pick up failed messages. If this was implemented as a synchronous flow, overall latency would be longer and the order creation flow would be more prone to errors.

**Comment by jodafm** [comment]
Hey @nmoutschen 
Brilliant explanation.
Now I have a clear perspective of microservices communication.
Thank you!

**Comment by nmoutschen** [comment]
Glad to hear that! I'll be closing this ticket for now but if you have other questions, feel free to create a new ticket or [ping me on Twitter](https://twitter.com/NMoutschen).
