### ISSUE TITLE
[Question] Branching Strategy CI/CD

### ISSUE THREAD

**Issue by patrickwerz** [aws-samples/aws-serverless-ecommerce-platform#136]
Hi Nicolas, 
I watched Marcias video about this project and really liked it. 
I have a question regarding your branching strategy: Maybe this could be incorporated into the decision log as well?

https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/pipeline/README.md

"Whenever there is a commit pushed to the master branch...":
1. Question: How do you test feature branches if you first have to merge them into master before they actually get deployed? 
2. Question:  What happens to pipelines with failing tests? Can they still be deployed to stg and prd?
3. Question: Is there a manual process before a commit gets deployed to prd? If not what is your opinion on that? 
4. Question: How do you ensure that always the latest commit is deployed to a stage? 

I am currently thinking about my branching strategy and the mapping of each branch to an aws environment. What is your take on this? Are there some best practices I should consider? 

Thanks in advance,
Patrick

P.S. I like your idea of using make files to wire up all the ci/cd processes. Do you know if they are working also on windows machines?

**Comment by nmoutschen** [comment]
Hi Patrick!

Thanks a lot for reaching out and glad you like the video! 😄 

## Question 1

I've seen different strategies for this: 

* One could be to trigger an automated deployment on feature branches. Whenever there's a new commit on the feature branch, it would update that environment.
* Another is to have environments per developers, and each developer can manually deploy (`make deploy` or `make deploy-{service}` for this sample). This is the approach I chose here. 😄 

What it means is that the CI/CD pipeline is a confirmation that tests are working, but developers **should** run the tests in their own environments.

Also, you can set the `ENVIRONMENT` environment variables to deploy multiple environments in the same AWS account. By default it's "dev", but you could set it to "feat-123" or "pr-123", etc.

## Question 2

The pipeline stops. 😄 The point of the pipeline is to catch these issues and prevent failures to get to production, so if a test fails, the entire pipeline stops. That said, this doesn't supports roll back in the test/staging environments. Instead, you'd need to do a roll-forward.

## Question 3

There's no manual process there, but [CodePipeline supports it](https://docs.aws.amazon.com/codepipeline/latest/userguide/approvals.html).

I'm a fan of using pull requests and mandatory code reviews before going into the main branch. Reviewers can also take the pull request and deploy it in a test environment (or you can have environments per features branches as mentioned above).

If you have these processes, the question is then "why have manual approval", since you already have manual and automated checks throughout the process. The risk with manual approval is that they could slow down the release cycle, e.g. waiting for someone to be out of a meeting/back from holidays/etc. Also, what are the expectations on the person approving the deployment? Should they do manual tests in staging? Is there a runbook with a list of tests to perform? If so, can we automate those tests?

Another reason to have manual approval could be because there are days/times when you don't want to deploy. But there are several ways to automate that in CodePipeline too.

## Question 4

This is a hard question. I didn't implement any consistency between environments yet (see the roll-forward part). Also, the latest commit might not be the latest commit we want to have in production, e.g. if there are tests failing. That said, you could have systems using SSM Parameter Store and keep the commit ID/timestamp for a given environment/service. If there are inconsistencies or other issues there, you could generate an alert.

By the way, here's an interesting article on how we use pipelines within Amazon: https://aws.amazon.com/builders-library/automating-safe-hands-off-deployments/

## Makefiles on Windows

When I'm coding on Windows, I use WSL2 *a lot*. I've been using Linux for over 15 years for development so my experience with Windows development is rather scarce. There is [NMake](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference?redirectedfrom=MSDN&view=vs-2019) to run the Makefiles, but I don't have experience with it.

This also uses bash scripts a lot, so you might need bash installed as well. That said, if you want to use specific languages in your project, you could re-implement the helper scripts in that language.

**Comment by patrickwerz** [comment]
Nicolas, thank you so much for taking the time and your comprehensive answer.
