### ISSUE TITLE
TemplateURL to dlq.yaml wrong

### ISSUE THREAD

**Issue by ljacobsson** [aws-samples/aws-serverless-ecommerce-platform#139]
The [TemplateURL](https://github.com/aws-samples/aws-serverless-ecommerce-platform/master/orders/template.yaml#L281) to dlq.yaml steps up one folder too many. This is true for all templates pulling in dlq.yaml.

Changing to `TemplateURL: ../shared/templates/dlq.yaml` works

**Comment by nmoutschen** [comment]
Hey Lars!

Thanks a lot for opening this issue!

There's a reason why it goes one folder more than expected. After the build phase, all elements are copied into the `{service}/build/` folder before the package phase. Thus the template will be in `orders/build/` instead of `orders/`. Because of that, the TemplateURL needs to go back 2 folders (`orders/build/../../shared/templates/dlq.yaml` which will resolve to `shared/templates/dlq.yaml`).

**Comment by ljacobsson** [comment]
Thanks for clarifying :-) 

I thought it was something like that going on, but couldn't find where it happened, but now I found it under `tools/build`.

I used this project when testing (I always do, it's great :-)) inclusion of nested stacks in [cfn-diagram](https://github.com/mhlabs/cfn-diagram), but it kept breaking when it couldn't find the dlq.yaml

For developers contributing to the SAM template, but not familiar with the build procedure I think it gets a bit confusing to point to not-yet-existing paths.

**Comment by nmoutschen** [comment]
Fair point! I'll create a PR with some comments in the templates that use the DLQ explaining why the path is like that.

**Comment by nmoutschen** [comment]
I put some explanations around that in https://github.com/aws-samples/aws-serverless-ecommerce-platform/pull/144
