### ISSUE TITLE
Question: API Gateway for service-to-service sync communication?

### ISSUE THREAD

**Issue by dashmug** [aws-samples/aws-serverless-ecommerce-platform#162]
I'd like to ask why API Gateway is used for service-to-service sync communication instead of direct Lambda-to-Lambda calls. Wouldn't it add additional latency?

Lambda-to-Lambda invocations is generally discouraged but isn't Lambda-to-API Gateway even worse?

**Comment by nmoutschen** [comment]
Hi @dashmug !

In short, it's a tradeoff between having interfaces that don't leak internal implementation versus cost/latency.

Since the communication is between different services, having API Gateway in the middle means there's a neutral API between the two services that gives the flexibility to make changes to the implementation. If it was Lambda to Lambda, it means that Lambda is now the external contract of that microservice, so I cannot change it to a direct integration, a Fargate container, etc.

On the other side, as you pointed out, it increases cost and latency. On top of two Lambda functions executing, you have additional latency and cost for API Gateway. It's similar to why Lambda to Lambda is generally discouraged: it doubles the cost.

In this case, if cost was a priority over decoupling the two microservices, you could have direct communication with Lambda from service A to DynamoDB in service B (e.g. for [the internal orders API](https://github.com/aws-samples/aws-serverless-ecommerce-platform/tree/master/orders)). It's the cheapest and most performant option, but that creates an even tighter coupling between the two microservices.

**Comment by dashmug** [comment]
Thank you @nmoutschen. It makes sense now. 

I will close this issue.
